### PR TITLE
- Addressed the vast majority of issues raised on https://trello.com/…

### PR DESCRIPTION
**Pull request by emilanca**
- Addressed the vast majority of issues raised on Andrew's review here https://trello.com/c/EtFhjsme/11-day-7-15
- Code optimizations
(Unit/functional tests will be supplied in the future.)

Please review the code as a whole as the initial prototype push didn't undergo a full team review and I'd like to get as many issues out of the way as possible.

Thanks,
Emil

### CODE REVIEW

**Comment by overtron** [comment]
this is still causing my kettle to crash if i open it via the mac app (only work if i open it via spoon.sh). Any thoughts about what might be causing this?

**Comment by emilanca** [comment]
@overtron 
I'll try to get a hold of a mac and test it there to see what's up - I'm assuming it's something minor. Meanwhile if you see any stacktrace being thrown after opening via spoon.sh on a mac, please share it.

Either way will look into this, thanks.

**Comment by overtron** [comment]
@emilanca figured out the issue with the mac and added a commit to fix it. Made the commit on master initially so I had to cherry pick it over to the dev branch

**Comment by emilanca** [comment]
@overtron cool Andrew, that Mac though I've requested should be helpful in the future anyway

**Comment by emilanca** [comment]
Pushed latest code on 0.2 branch, generalizing input fields and addressing most of the comments.
Thanks.

**Comment by overtron** [comment]
@emilanca A few things I noticed today
- I didn't get a prompted to save the transformation after updating the fields of the step. This is usually due to missing listeners.
- We should submit this step to the Pentaho Marketplace (so you can officially become a contributor). Look at the section on [registering a plugin](http://wiki.pentaho.com/display/EAI/Marketplace). Commit should look something [like this](https://github.com/pentaho/marketplace-metadata/commit/c7a43c5b65ad7bfa4b09c0df1dde5eba7195f582)

**Comment by emilanca** [comment]
ok @overtron thanks for providing info on the commit message standards.

@nnairftb - for sure - makes sense, will try to keep the commits small whenever I can

**Pull request closed without merging**
